// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "j30att/observer/internal/server/model"

	mock "github.com/stretchr/testify/mock"
)

// MockMetricsLister is an autogenerated mock type for the MetricsLister type
type MockMetricsLister struct {
	mock.Mock
}

type MockMetricsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsLister) EXPECT() *MockMetricsLister_Expecter {
	return &MockMetricsLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function with no fields
func (_m *MockMetricsLister) List() []model.Metrics {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Metrics
	if rf, ok := ret.Get(0).(func() []model.Metrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Metrics)
		}
	}

	return r0
}

// MockMetricsLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMetricsLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockMetricsLister_Expecter) List() *MockMetricsLister_List_Call {
	return &MockMetricsLister_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockMetricsLister_List_Call) Run(run func()) *MockMetricsLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsLister_List_Call) Return(_a0 []model.Metrics) *MockMetricsLister_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsLister_List_Call) RunAndReturn(run func() []model.Metrics) *MockMetricsLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsLister creates a new instance of MockMetricsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsLister {
	mock := &MockMetricsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
