package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	generateResetComment = "generate:reset"
	generatedFileName    = "reset.gen.go"
	resetterType         = "interface{ Reset() }"
)

type resetStruct struct {
	Name   string
	Fields []*ast.Field
}

type packageResetData struct {
	Dir     string
	Name    string
	Structs []resetStruct
}

func main() {
	flag.Parse()

	root := "."
	if flag.NArg() > 0 {
		root = flag.Arg(0)
	}

	if err := generate(root); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(root string) error {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return err
	}

	var packages []packageResetData
	err = filepath.WalkDir(absRoot, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.IsDir() {
			return nil
		}
		if shouldSkipDir(entry.Name()) {
			return filepath.SkipDir
		}

		pkgData, err := parsePackageDir(path)
		if err != nil {
			return err
		}
		if len(pkgData.Structs) > 0 {
			packages = append(packages, pkgData)
		}

		return nil
	})
	if err != nil {
		return err
	}

	for _, pkgData := range packages {
		if err := writeGeneratedFile(pkgData); err != nil {
			return err
		}
	}

	return nil
}

func shouldSkipDir(name string) bool {
	switch name {
	case ".git", "vendor":
		return true
	default:
		return strings.HasPrefix(name, ".")
	}
}

func parsePackageDir(dir string) (packageResetData, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, shouldParseFile, parser.ParseComments)
	if err != nil {
		return packageResetData{}, err
	}
	if len(pkgs) == 0 {
		return packageResetData{}, nil
	}
	if len(pkgs) > 1 {
		names := make([]string, 0, len(pkgs))
		for name := range pkgs {
			names = append(names, name)
		}
		sort.Strings(names)
		return packageResetData{}, fmt.Errorf("%s: multiple non-test packages found: %s", dir, strings.Join(names, ", "))
	}

	for _, pkg := range pkgs {
		pkgData := packageResetData{
			Dir:  dir,
			Name: pkg.Name,
		}

		files := make([]string, 0, len(pkg.Files))
		for filename := range pkg.Files {
			files = append(files, filename)
		}
		sort.Strings(files)

		for _, filename := range files {
			file := pkg.Files[filename]
			pkgData.Structs = append(pkgData.Structs, findResetStructs(file)...)
		}

		sort.Slice(pkgData.Structs, func(i, j int) bool {
			return pkgData.Structs[i].Name < pkgData.Structs[j].Name
		})

		return pkgData, nil
	}

	return packageResetData{}, nil
}

func shouldParseFile(info fs.FileInfo) bool {
	name := info.Name()
	return !info.IsDir() &&
		strings.HasSuffix(name, ".go") &&
		!strings.HasSuffix(name, "_test.go") &&
		name != generatedFileName
}

func findResetStructs(file *ast.File) []resetStruct {
	var structs []resetStruct
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok || !hasGenerateResetComment(genDecl.Doc, typeSpec.Doc) {
				continue
			}

			structs = append(structs, resetStruct{
				Name:   typeSpec.Name.Name,
				Fields: structType.Fields.List,
			})
		}
	}

	return structs
}

func hasGenerateResetComment(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, comment := range group.List {
			text := strings.TrimSpace(comment.Text)
			text = strings.TrimPrefix(text, "//")
			text = strings.TrimPrefix(text, "/*")
			text = strings.TrimSuffix(text, "*/")
			if strings.TrimSpace(text) == generateResetComment {
				return true
			}
		}
	}

	return false
}

func writeGeneratedFile(pkgData packageResetData) error {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by cmd/reset; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "package %s\n\n", pkgData.Name)

	for _, strct := range pkgData.Structs {
		writeResetMethod(&out, strct)
	}

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return fmt.Errorf("%s: format generated source: %w\n%s", pkgData.Dir, err, out.String())
	}

	return os.WriteFile(filepath.Join(pkgData.Dir, generatedFileName), formatted, 0o644)
}

func writeResetMethod(out *bytes.Buffer, strct resetStruct) {
	fmt.Fprintf(out, "func (r *%s) Reset() {\n", strct.Name)
	fmt.Fprintln(out, "if r == nil {")
	fmt.Fprintln(out, "return")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)

	for _, field := range strct.Fields {
		if len(field.Names) == 0 {
			name, ok := embeddedFieldName(field.Type)
			if !ok {
				continue
			}
			writeResetStatements(out, "r."+name, field.Type)
			continue
		}

		for _, name := range field.Names {
			writeResetStatements(out, "r."+name.Name, field.Type)
		}
	}

	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func embeddedFieldName(expr ast.Expr) (string, bool) {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name, true
	case *ast.SelectorExpr:
		return t.Sel.Name, true
	case *ast.StarExpr:
		return embeddedFieldName(t.X)
	default:
		return "", false
	}
}

func writeResetStatements(out *bytes.Buffer, access string, expr ast.Expr) {
	switch t := expr.(type) {
	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(out, "%s = %s[:0]\n", access, access)
			return
		}
		writeZeroAssignment(out, access, expr)
	case *ast.MapType:
		fmt.Fprintf(out, "clear(%s)\n", access)
	case *ast.StarExpr:
		writePointerReset(out, access, t.X)
	case *ast.StructType:
		writeAnonymousStructReset(out, access, t)
	case *ast.Ident:
		if isPrimitiveIdent(t.Name) {
			writeZeroAssignment(out, access, expr)
			return
		}
		writeResetterOrZero(out, access, expr, "&"+access)
	case *ast.SelectorExpr:
		writeResetterOrZero(out, access, expr, "&"+access)
	case *ast.InterfaceType:
		writeZeroAssignment(out, access, expr)
	default:
		writeZeroAssignment(out, access, expr)
	}
}

func writePointerReset(out *bytes.Buffer, access string, expr ast.Expr) {
	fmt.Fprintf(out, "if %s != nil {\n", access)
	switch t := expr.(type) {
	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(out, "*%s = (*%s)[:0]\n", access, access)
		} else {
			writeZeroAssignment(out, "*"+access, expr)
		}
	case *ast.MapType:
		fmt.Fprintf(out, "clear(*%s)\n", access)
	case *ast.StarExpr:
		writePointerReset(out, "*"+access, t.X)
	case *ast.StructType:
		writeAnonymousStructReset(out, "*"+access, t)
	case *ast.Ident:
		if isPrimitiveIdent(t.Name) {
			writeZeroAssignment(out, "*"+access, expr)
		} else {
			writeResetterOrZero(out, "*"+access, expr, access)
		}
	case *ast.SelectorExpr:
		writeResetterOrZero(out, "*"+access, expr, access)
	case *ast.InterfaceType:
		writeZeroAssignment(out, "*"+access, expr)
	default:
		writeZeroAssignment(out, "*"+access, expr)
	}
	fmt.Fprintln(out, "}")
}

func writeAnonymousStructReset(out *bytes.Buffer, access string, strct *ast.StructType) {
	for _, field := range strct.Fields.List {
		if len(field.Names) == 0 {
			name, ok := embeddedFieldName(field.Type)
			if !ok {
				continue
			}
			writeResetStatements(out, access+"."+name, field.Type)
			continue
		}

		for _, name := range field.Names {
			writeResetStatements(out, access+"."+name.Name, field.Type)
		}
	}
}

func writeResetterOrZero(out *bytes.Buffer, access string, expr ast.Expr, resetterExpr string) {
	fmt.Fprintf(out, "if resetter, ok := any(%s).(%s); ok {\n", resetterExpr, resetterType)
	fmt.Fprintln(out, "resetter.Reset()")
	fmt.Fprintln(out, "} else {")
	writeZeroAssignment(out, access, expr)
	fmt.Fprintln(out, "}")
}

func writeZeroAssignment(out *bytes.Buffer, access string, expr ast.Expr) {
	fmt.Fprintf(out, "%s = *new(%s)\n", access, types.ExprString(expr))
}

func isPrimitiveIdent(name string) bool {
	switch name {
	case "bool",
		"string",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return true
	default:
		return false
	}
}
