// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	repository "j30att/observer/internal/agent/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockCollector is an autogenerated mock type for the Collector type
type MockCollector struct {
	mock.Mock
}

type MockCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollector) EXPECT() *MockCollector_Expecter {
	return &MockCollector_Expecter{mock: &_m.Mock}
}

// Collect provides a mock function with given fields: store
func (_m *MockCollector) Collect(store *repository.MetricsRepository) error {
	ret := _m.Called(store)

	if len(ret) == 0 {
		panic("no return value specified for Collect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*repository.MetricsRepository) error); ok {
		r0 = rf(store)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCollector_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type MockCollector_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - store *repository.MetricsRepository
func (_e *MockCollector_Expecter) Collect(store interface{}) *MockCollector_Collect_Call {
	return &MockCollector_Collect_Call{Call: _e.mock.On("Collect", store)}
}

func (_c *MockCollector_Collect_Call) Run(run func(store *repository.MetricsRepository)) *MockCollector_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*repository.MetricsRepository))
	})
	return _c
}

func (_c *MockCollector_Collect_Call) Return(_a0 error) *MockCollector_Collect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollector_Collect_Call) RunAndReturn(run func(*repository.MetricsRepository) error) *MockCollector_Collect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollector creates a new instance of MockCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollector {
	mock := &MockCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
