// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "j30att/observer/internal/server/model"

	mock "github.com/stretchr/testify/mock"
)

// MockMetricsSaver is an autogenerated mock type for the MetricsSaver type
type MockMetricsSaver struct {
	mock.Mock
}

type MockMetricsSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsSaver) EXPECT() *MockMetricsSaver_Expecter {
	return &MockMetricsSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: metrics
func (_m *MockMetricsSaver) Save(metrics []model.Metrics) error {
	ret := _m.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Metrics) error); ok {
		r0 = rf(metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMetricsSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - metrics []model.Metrics
func (_e *MockMetricsSaver_Expecter) Save(metrics interface{}) *MockMetricsSaver_Save_Call {
	return &MockMetricsSaver_Save_Call{Call: _e.mock.On("Save", metrics)}
}

func (_c *MockMetricsSaver_Save_Call) Run(run func(metrics []model.Metrics)) *MockMetricsSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.Metrics))
	})
	return _c
}

func (_c *MockMetricsSaver_Save_Call) Return(_a0 error) *MockMetricsSaver_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsSaver_Save_Call) RunAndReturn(run func([]model.Metrics) error) *MockMetricsSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsSaver creates a new instance of MockMetricsSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsSaver {
	mock := &MockMetricsSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
